services:
  erm_app:
    build:
      dockerfile: docker/Dockerfile
    container_name: erm_service
    command: sh -c "aerich upgrade && uvicorn src.app.main:app --host 0.0.0.0 --port 8021 --reload"
    env_file: .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/firebase-credentials.json
    restart: always
    volumes:
      - .:/app
      - /home/hire10x/configs:/app/configs
    working_dir: /app
    networks:
      - apisix-net
      - shared_network
      - db_network
    dns:
      - 8.8.8.8
      - 1.1.1.1

networks:
  apisix-net:
    external: true
    name: apache_apisix-net

  db_network:
    external: true
    name: db_network

  shared_network:
    external: true

    name: shared_network