services:
  base_app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: base_app
    command:
      [
        "uvicorn",
        "src.app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8082",
        "--reload",
      ]
    env_file: .env
    restart: always
    volumes:
      - ..:/app
      # Mount SQLite database file to persist data
      - ./db.sqlite3:/app/db.sqlite3
    working_dir: /app
    networks:
      - db_network
      - shared_network

  base_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: base_worker
    restart: always
    command:
      [
        "taskiq",
        "worker",
        "src.app.worker:broker",
        "-fsd",
        "-tp",
        "src/**/*_tasks.py",
      ]
    env_file: .env
    volumes:
      - ..:/app
      # Mount SQLite database file to persist data
      - ./db.sqlite3:/app/db.sqlite3
    networks:
      - db_network
      - shared_network

networks:
  db_network:
    external: true
    name: db_network
  shared_network:
    external: true
    name: my_shared_network
